teamproject/accountapp/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('onlymember/', views.only_member, name="onlymember"),
    path('index2/', views.index2, name="index2"),
]

teamproject/qnaapp/urls.py
from django.urls import path
from . import views

app_name='qnaapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name="question_modify"),
    path('question/delete/<int:question_id>/', views.question_delete,  name='question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name="answer_modify"),
    path('answer/delete/<int:answer_id>/', views.answer_delete,  name='answer_delete'),
]

teamproject/teamproject/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appfordog/qna/', include('qnaapp.urls')),
    path('appfordog/', include('mainapp.urls')),
    path('appfordog/account/', include('accountapp.urls')),
]

teamproject/templates/dogapp/login_index.html
{% extends 'login_base.html' %}

{% load static %}

{% block content7 %}
<section class="inner-page">
  <div class="container">
    <div class="row mt-5">
         <div class="col-12 text-center">
             {% if not logineduser %}
                <h3>로그아웃 되었개! 멍멍!</h3>
             {% else %}
                <h3>로그인 되었개! 멍멍!</h3>
             {% endif %}
         </div>
    </div>
  </div>
</section>
{% endblock %}

teamproject/templates/dogapp/login_index2.html
{% extends 'login_base.html' %}

{% load static %}

{% block content7 %}
<section class="inner-page">
  <div class="container">
    <div class="row mt-5">
         <div class="col-12 text-center">
                <h3>회원 가입 되었개! 멍멍!</h3>
         </div>
    </div>
  </div>
</section>
{% endblock %}

teamproject/templates/dogapp/login_logout.html
{% extends 'login_base.html' %}

{% load static %}

{% block content7 %}
    <section class="button_log">
      <div class="container">
          <div class="row mt-5">
              <div class="col-12 text-center" style="color:#000000;">
                  <h1>로그아웃 되었개</h1>
              </div>
          </div>
      </div>
    </section>
{% endblock %}

teamproject/templates/dogapp/login_register.html
{% extends 'login_base.html' %}

{% load static %}

{% block content7 %}
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">
        <div class="d-flex justify-content-between align-items-center">
          <h2>Sign Up</h2>
          <ol>
            <li><a href="/appfordog/">Home</a></li>
            <li>Sign Up</li>
          </ol>
        </div>
         <div class="row mt-5">
                <div class="col-12 text-center" style="color:red">
                 {{error}}
                </div>
         </div>
      </div>
    </section><!-- End Breadcrumbs -->
    <section class="button1">
      <div class="container">
            <div class="row mt-5">
                <div class="col-12 text-center">
                    <h1>회원가입</h1>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-12 text-center" style="color:red">
                    {{error}}
                </div>
            </div>
            <div style="display: flex; flex-direction: row; justify-content: center; align-items: center;">
                <div class="row mt-5">
                    <div class="col-12">
                        <form method="POST" action="{% url 'account:register' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="useremail">사용자 이메일</label>
                                <input type="email" class="form-control"  placeholder="사용자 아이디" name="useremail" required>
                                <small id="emailHelp" class="form-text text-muted">이메일 주소를 아이디로 사용합니다.</small>
                            </div><br>
                            <div class="form-group">
                                <label for="username">사용자 성과 이름</label>
                                <div style="column-count:2;">
                                    <div>
                                        <input type="text" class="form-control"  placeholder="성" name="lastname" required>
                                    </div>
                                    <div>
                                        <input type="text" class="form-control"  placeholder="이름" name="firstname" required>
                                    </div>
                                </div>
                            </div><br>
                            <div class="form-group">
                                <label for="password">비밀번호</label>
                                <input type="password" class="form-control" placeholder="비밀번호" name="password" required>
                            </div><br>
                            <div class="form-group">
                                <label for="re-password">비밀번호 확인</label>
                                <input type="password" class="form-control" placeholder="비밀번호 확인" name="re-password" required>
                            </div><br>
                            <button type="submit" class="btn btn-primary" style="float: right; border: 0; background: #c6e1ff; color:#000000;">회원가입</button>
                        </form>
                    </div>
                </div>
            </div>
      </div>
    </section>
{% endblock %}

teamproject/templates/dogapp/sort_end.html
{% extends 'sort_base.html' %}

{% load static %}

{% block content2 %}
    <form id="dataform" method="get">
          <input name="result_r1" style="display: none;" type="text" value="{{  results.result_r1  }}">
          <input name="result_m1" style="display: none;" type="text" value="{{  results.result_m1  }}">
          <input name="result_r2" style="display: none;" type="text" value="{{  results.result_r2  }}">
          <input name="result_m2" style="display: none;" type="text" value="{{  results.result_m2  }}">
          <input name="category_id" style="display: none;" type="text" value="{{  category_id  }}">
          <input name="type_id" style="display: none;" type="text" value="{{  type_id  }}">
          <input name="state_id" style="display: none;" type="text" value="{{  state_id  }}">
          <input name="city_id" style="display: none;" type="text" value="{{  city_id  }}">
    </form>
  <!-- ======= Counts Section ======= -->
    <section class="counts" id="counts">
        <div class="container" data-aos="fade-up">
          <div class="row no-gutters">
            <div class="image col-xl-5 d-flex align-items-stretch justify-content-center justify-content-lg-start" data-aos="fade-right" data-aos-delay="100"></div>
             <div data-aos="fade-left" data-aos-delay="100">
              <div class="content d-flex flex-column justify-content-center">
                <h3>얼른 출발 하시개!</h3>
                    <div id="map" style="width:100%; height:600px;"></div>
                  <script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=6075751d111977dfe10aaa2dec967efd"></script>
                    <script>
                        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
                            mapOption = {
                                center: new kakao.maps.LatLng({{ avg_lat }}, {{ avg_lng }}), // 지도의 중심 좌표
                                level: 8 // 지도의 확대 레벨
                                }

                        // 지도를 생성 한다
                        var map = new kakao.maps.Map(mapContainer, mapOption);

                        var positions = [
                            {% for dogplace in total_result %}
                            {
                                content: '<div>{{  dogplace.name  }}</div><br><div>{{  dogplace.city.state.statename  }} {{  dogplace.city.cityname  }} {{  dogplace.addr  }}</div>',
                                latlng: new kakao.maps.LatLng({{  dogplace.lat  }}, {{  dogplace.lon  }})
                            },
                            {% endfor %}
                        ];

                        for (var i = 0; i < positions.length; i ++) {
                            // 마커를 생성합니다
                            var marker = new kakao.maps.Marker({
                                map: map, // 마커를 표시할 지도
                                position: positions[i].latlng // 마커의 위치
                            });

                            // 마커에 표시할 인포윈도우를 생성합니다
                            var infowindow = new kakao.maps.InfoWindow({
                                content: positions[i].content // 인포윈도우에 표시할 내용
                            });

                            // 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다
                            // 이벤트 리스너로는 클로저를 만들어 등록합니다
                            // for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
                            kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
                            kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));
                        }

                        // 인포윈도우를 표시하는 클로저를 만드는 함수입니다
                        function makeOverListener(map, marker, infowindow) {
                            return function() {
                                infowindow.open(map, marker);
                            };
                        }

                        // 인포윈도우를 닫는 클로저를 만드는 함수입니다
                        function makeOutListener(infowindow) {
                            return function() {
                                infowindow.close();
                            };
                        }

                        // 지도에 확대 축소 컨트롤을 생성한다
                        var zoomControl = new kakao.maps.ZoomControl();

                        // 지도의 우측에 확대 축소 컨트롤을 추가한다
                        map.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);

                    </script>
                 </div>
              </div>
              <div class="column" style="column-count: 2;">
                 <div id="image">
                      <img alt="" src="{% static 'img/car_dog1.jpg' %}" style="height: 100%;">
                 </div>
                 <div id="count-box">
                     <div style="padding: 15px 0 0 0; margin: 0 0 0 50px; font-family: 'Raleway', sans-serif; font-size: 36px; color: #3b3b3b; width: 760px;">
                         총 검색 결과:<span class="purecounter" data-purecounter-duration="0.5" data-purecounter-end="{{  len_result  }}" data-purecounter-start="0" style="font-size: 36px;  line-height: 30px;  font-weight: 700;  color: #c6e1ff;  margin-left: 20px; "></span>
                         <div class="container">
                             <div onscroll="myFunction()" style="width: 50%; height: 530px; overflow: scroll;">
                                 {% for dogplace in total_result %}
                                 <tr>
                                     <td class="text-left">
                                         <a style="font-size:20px; font-weight:800">{{  dogplace.name  }}</a>
                                         <p style="font-size:13px">{{dogplace.type.typename}}<br>{{ dogplace.city.state.statename }} {{ dogplace.city.cityname }} {{  dogplace.addr  }}</p>
                                     </td>
                                 {% endfor %}
                                 </tr>
                             </div>
                         </div>
                     </div>
                 </div>
              </div>
          </div>
        </div>
    </section><!-- End Counts Section -->
{% endblock %}

teamproject/templates/dogapp/sort_end_hu.html
{% extends 'sort_base.html' %}

{% load static %}

{% block content2 %}
    <form id="dataform" method="get">
          <input name="result_r1" style="display: none;" type="text" value="{{  results.result_r1  }}">
          <input name="category_id" style="display: none;" type="text" value="{{  category_id  }}">
          <input name="type_id" style="display: none;" type="text" value="29">
    </form>
  <!-- ======= Counts Section ======= -->
    <section class="counts" id="counts">
        <div class="container" data-aos="fade-up">
          <div class="row no-gutters">
            <div class="image col-xl-5 d-flex align-items-stretch justify-content-center justify-content-lg-start" data-aos="fade-right" data-aos-delay="100"></div>
             <div data-aos="fade-left" data-aos-delay="100">
              <div class="content d-flex flex-column justify-content-center">
                <h3>얼른 출발 하시개!</h3>
                    <div id="map" style="width:100%; height:600px;"></div>
                  <script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=6075751d111977dfe10aaa2dec967efd"></script>
                    <script>
                        var mapContainer = document.getElementById('map'), // 지도를 표시할 div
                            mapOption = {
                                center: new kakao.maps.LatLng({{ avg_lat }}, {{ avg_lng }}), // 지도의 중심 좌표
                                level: 12 // 지도의 확대 레벨
                            };

                        // 지도를 생성 한다
                        var map = new kakao.maps.Map(mapContainer, mapOption);

                        var positions = [
                            {% for dogplace in total_result %}
                            {
                                content: '<div>{{  dogplace.name  }}</div><br><div>{{  dogplace.city.state.statename  }} {{  dogplace.city.cityname  }} {{  dogplace.addr  }}</div>',
                                latlng: new kakao.maps.LatLng({{  dogplace.lat  }}, {{  dogplace.lon  }})
                            },
                            {% endfor %}
                        ];

                        for (var i = 0; i < positions.length; i ++) {
                            // 마커를 생성합니다
                            var marker = new kakao.maps.Marker({
                                map: map, // 마커를 표시할 지도
                                position: positions[i].latlng // 마커의 위치
                            });

                            // 마커에 표시할 인포윈도우를 생성합니다
                            var infowindow = new kakao.maps.InfoWindow({
                                content: positions[i].content // 인포윈도우에 표시할 내용
                            });

                            // 마커에 mouseover 이벤트와 mouseout 이벤트를 등록합니다
                            // 이벤트 리스너로는 클로저를 만들어 등록합니다
                            // for문에서 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
                            kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
                            kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));
                        }

                        // 인포윈도우를 표시하는 클로저를 만드는 함수입니다
                        function makeOverListener(map, marker, infowindow) {
                            return function() {
                                infowindow.open(map, marker);
                            };
                        }

                        // 인포윈도우를 닫는 클로저를 만드는 함수입니다
                        function makeOutListener(infowindow) {
                            return function() {
                                infowindow.close();
                            };
                        }

                        // 지도에 확대 축소 컨트롤을 생성한다
                        var zoomControl = new kakao.maps.ZoomControl();

                        // 지도의 우측에 확대 축소 컨트롤을 추가한다
                        map.addControl(zoomControl, kakao.maps.ControlPosition.RIGHT);

                    </script>
                 </div>
              </div>
              <div class="column" style="column-count: 2;">
                 <div id="image">
                      <img alt="" src="{% static 'img/car_dog1.jpg' %}" style="height: 100%;">
                 </div>
                 <div id="count-box">
                     <div style="padding: 15px 0 0 0; margin: 0 0 0 50px; font-family: 'Raleway', sans-serif; font-size: 36px; color: #3b3b3b; width: 760px;">
                         총 검색 결과:<span class="purecounter" data-purecounter-duration="0.5" data-purecounter-end="{{  len_result  }}" data-purecounter-start="0" style="font-size: 36px;  line-height: 30px;  font-weight: 700;  color: #c6e1ff;  margin-left: 20px; "></span>
                         <div class="container">
                             <div onscroll="myFunction()" style="width: 50%; height: 530px; overflow: scroll;">
                                 {% for dogplace in total_result %}
                                 <tr>
                                     <td class="text-left">
                                         <a style="font-size:20px; font-weight:800">{{  dogplace.name  }}</a>
                                         <p style="font-size:13px">{{ dogplace.city.state.statename }} {{ dogplace.city.cityname }} {{  dogplace.addr  }}</p>
                                     </td>
                                 {% endfor %}
                                 </tr>
                             </div>
                         </div>
                     </div>
                 </div>
              </div>
          </div>
        </div>
    </section><!-- End Counts Section -->
{% endblock %}

teamproject/templates/dogapp/sort_m1_3.html
{% extends 'sort_m1_base.html' %}

{% load static %}

{% block content4 %}
  <div class="multi">
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="17" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;" name="result_m1" value="실내">실내만</h4>
      </div>
      <div class="icon-box mt-5"data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="18" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="실외">실내/실외</h4>
      </div>
  </div>
{% endblock %}

teamproject/templates/dogapp/sort_m1_4.html
{% extends 'sort_m1_base.html' %}

{% load static %}

{% block content4 %}
  <div class="multi">
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="1" ><input type="checkbox"  style="width:30px; height:30px; margin-right: 60px;" name="result_m1" value="글램핑">애견 동반 가능 글램핑</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="2" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="애견 펜션">애견 펜션</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="4" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="펜션">애견 동반 가능 펜션</h4>
      </div>
      <div class="icon-box mt-5 " data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="3" ><input type="checkbox"  style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="캠핑장">애견 동반 가능 캠핑장</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="5" ><input type="checkbox"  style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="호텔">애견 동반 가능 호텔</h4>
      </div>
  </div>
{% endblock %}

teamproject/templates/dogapp/sort_m1_5.html
{% extends 'sort_m1_base.html' %}

{% load static %}

{% block content4 %}
  <div class="multi">
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="6" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;" name="result_m1" value="무료 반려견 놀이터">무료 반려견 놀이터</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="12" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;" name="result_m1" value="유료 반려견 놀이터">유료 반려견 놀이터</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="7" ><input type="checkbox" style="width:30px; height:30px; margin-right: 30px;"  name="result_m1" value="반려 동반 가능 복합 시설">반려 동반 가능 복합 시설</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="8" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="반려 동반 가능 영화관">반려 동반 가능 영화관</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="9" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="반려 동반 가능 명소">반려 동반 가능 명소</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="10" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="반려견 수영장">반려견 수영장</h4>
      </div>
      <div class="icon-box mt-5" data-aos="zoom-in" data-aos-delay="150">
        <h4 style="color: #000000"><input type="checkbox"  style="display:none;" name="type_id" value="11" ><input type="checkbox" style="width:30px; height:30px; margin-right: 60px;"  name="result_m1" value="반려견 테마파크">반려견 테마파크</h4>
      </div>
  </div>
{% endblock %}

teamproject/templates/dogapp/sort_m2_1.html
{% extends 'sort_m2_base.html' %}

{% load static %}

{% block content5 %}
  <div class="col-lg-4 col-md-6 portfolio-item filter-web">
    <div class="portfolio-info">
        <div class="row aos-init aos-animate" data-aos="fade-up" data-aos-delay="200" style="width: 1290px;">
            <ul id="portfolio-filters">
              <li><input type="checkbox"  style="display:none;" name="city_id" value="19" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="중구">중구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="35" ><input type="checkbox" style="width: 25px; height: 23px; margin: 12px;" name="result_m2" value="종로구">종로구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="18" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="용산구">용산구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="28" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="성동구">성동구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="16" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="광진구">광진구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="64" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="동대문구">동대문구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="31" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="중랑구">중랑구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="29" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="성북구">성북구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="33" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="노원구">노원구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="48" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="은평구">은평구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="22" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="서대문구">서대문구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="17" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="마포구">마포구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="45" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="양천구">양천구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="42" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="강서구">강서구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="32" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="구로구">구로구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="54" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="금천구">금천구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="34" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="영등포구">영등포구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="44" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="동작구">동작구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="43" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="관악구">관악구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="27" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="서초구">서초구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="15" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="강남구">강남구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="30" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="송파구">송파구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="26" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="강동구">강동구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="41" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="강북구">강북구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="63" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="도봉구">도봉구</li>
            </ul>
        </div>
    </div>
  </div>
{% endblock %}

teamproject/templates/dogapp/sort_m2_2.html
{% extends 'sort_m2_base.html' %}

{% load static %}

{% block content5 %}
<div class="col-lg-4 col-md-6 portfolio-item filter-web">
  <div class="portfolio-info">
      <div class="row aos-init aos-animate" data-aos="fade-up" data-aos-delay="200" style="width: 1290px;">
          <ul id="portfolio-filters">
              <li><input type="checkbox"  style="display:none;" name="city_id" value="80" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="중구">중구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="81" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="동구">동구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="65" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="미추홀구">미추홀구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="20" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="연수구">연수구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="36" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="남동구">남동구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="47" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="부평구">부평구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="46" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="계양구">계양구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="49" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="서구">서구</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="10" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="남동구-강화군">남동구-강화군</li>
              <li><input type="checkbox"  style="display:none;" name="city_id" value="11" ><input type="checkbox" style="width: 23px; height: 23px; margin: 12px;" name="result_m2" value="남동구-옹진군">남동구-옹진군</li>
         </ul>
      </div>
  </div>
</div>
{% endblock %}